apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"operator.catalysts.cc/v1alpha1","kind":"LeoCertificate","metadata":{"name":"example.org"},"spec":{"domain":"example.org"}},{"apiVersion":"operator.catalysts.cc/v1alpha1","kind":"LeoConfig","metadata":{"name":"default"},"spec":{"account":{"email":"admin@example.org"},"production":true,"provider":{"acmeDNS":{"url":"https://acme-dns.catalysts.cc"}}}}]'
    capabilities: Full Lifecycle
    repository: https://git.internal.catalysts.cc/catalysts-infrastructure/openshift/leo-operator
  name: leo-operator.v0.0.1
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: LeoCertificate
      name: leocertificates.operator.catalysts.cc
      version: v1alpha1
      displayName: Leo Certificate
    - kind: LeoConfig
      name: leoconfigs.operator.catalysts.cc
      version: v1alpha1
      displayName: Leo Config
  description: The Leo Operator can automatically obtain and renew Let's Encrypt certificates.
  displayName: Leo Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - leo-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - operator.catalysts.cc
          resources:
          - '*'
          - leocertificates
          verbs:
          - '*'
        serviceAccountName: leo-operator
      deployments:
      - name: leo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: leo-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: leo-operator
            spec:
              containers:
              - command:
                - leo-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: leo-operator
                image: image-registry.openshift-image-registry.svc:5000/catalysts-operators/leo-operator:v0.0.1
                imagePullPolicy: Always
                name: leo-operator
                resources: {}
              serviceAccountName: leo-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  keywords:
  - lets encrypt
  - certificate
  - acme
  - acmedns
  maintainers:
  - email: wolfgang.ebner@catalysts.cc
    name: Wolfgang Ebner
  minKubeVersion: v1.11.0
  provider:
    name: Catalysts GmbH
  version: 0.0.1
