// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoAccount) DeepCopyInto(out *LeoAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoAccount.
func (in *LeoAccount) DeepCopy() *LeoAccount {
	if in == nil {
		return nil
	}
	out := new(LeoAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoCertificate) DeepCopyInto(out *LeoCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoCertificate.
func (in *LeoCertificate) DeepCopy() *LeoCertificate {
	if in == nil {
		return nil
	}
	out := new(LeoCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeoCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoCertificateList) DeepCopyInto(out *LeoCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LeoCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoCertificateList.
func (in *LeoCertificateList) DeepCopy() *LeoCertificateList {
	if in == nil {
		return nil
	}
	out := new(LeoCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeoCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoCertificateSpec) DeepCopyInto(out *LeoCertificateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoCertificateSpec.
func (in *LeoCertificateSpec) DeepCopy() *LeoCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(LeoCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoCertificateStatus) DeepCopyInto(out *LeoCertificateStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoCertificateStatus.
func (in *LeoCertificateStatus) DeepCopy() *LeoCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(LeoCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoConfig) DeepCopyInto(out *LeoConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoConfig.
func (in *LeoConfig) DeepCopy() *LeoConfig {
	if in == nil {
		return nil
	}
	out := new(LeoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeoConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoConfigList) DeepCopyInto(out *LeoConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LeoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoConfigList.
func (in *LeoConfigList) DeepCopy() *LeoConfigList {
	if in == nil {
		return nil
	}
	out := new(LeoConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeoConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoConfigSpec) DeepCopyInto(out *LeoConfigSpec) {
	*out = *in
	out.Account = in.Account
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoConfigSpec.
func (in *LeoConfigSpec) DeepCopy() *LeoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LeoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoConfigStatus) DeepCopyInto(out *LeoConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoConfigStatus.
func (in *LeoConfigStatus) DeepCopy() *LeoConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LeoConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoProvider) DeepCopyInto(out *LeoProvider) {
	*out = *in
	out.AcmeDNS = in.AcmeDNS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoProvider.
func (in *LeoProvider) DeepCopy() *LeoProvider {
	if in == nil {
		return nil
	}
	out := new(LeoProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeoProviderAcmeDNS) DeepCopyInto(out *LeoProviderAcmeDNS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeoProviderAcmeDNS.
func (in *LeoProviderAcmeDNS) DeepCopy() *LeoProviderAcmeDNS {
	if in == nil {
		return nil
	}
	out := new(LeoProviderAcmeDNS)
	in.DeepCopyInto(out)
	return out
}
