kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leo-operator
subjects:
- kind: ServiceAccount
  name: leo-operator
  namespace: catalysts-operators
roleRef:
  kind: ClusterRole
  name: leo-operator
  apiGroup: rbac.authorization.k8s.io
